name: dart2048
description: The 2048 game written in Dart.
version: 1.0.0
homepage: https://github.com/whoiscc/dart2048
author: whoiscc <correctizer@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test:
  mockito:
